import { Translation } from '@/models/interfaces';

const es: Partial<Translation> = {
  workExperience: 'Experiencia Laboral',
  education: 'Educación y Certificaciones',
  skills: 'Habilidades',
  agile: 'Metodologias Agiles',
  en: 'EN',
  es: 'ES',
  dropdownOptionsDownload: 'Descargar CV',
  dropdownOptionsClone: 'Ver código',
  skillsDescription:
    'Poseo un conjunto diverso de habilidades que me permiten entregar trabajo de alta calidad.',
  workExperienceDescription:
    'Explora mi trayectoria profesional y los diversos roles que he desempeñado.',
  educationDescription:
    'Explora mi trayectoria educativa y los títulos que he obtenido.',
  email: 'Email',
  phone: 'Telefono',
  Projects: 'Proyectos',
  languages: 'Idiomas',
  clickAction: 'Ir a la sección',
  downloadAction: 'Click para descargar',
  copyAction: 'Click para copiar',
  toggleThemeAction: 'Cambiar tema',
  changeLanguageAction: 'Cambiar idioma',
  scrollToHomeTooltip: 'Ir a inicio',
  scrollToWorkTooltip: 'Ir a Experiencia laboral',
  scrollToEducationTooltip: 'Ir a educación',
  scrollToSkillsTooltip: 'Ir a habilidades',
  scrollToProjectsTooltip: 'Ir a proyectos',
  createNodeButtonTooltip: 'Crear nodo',
  removeNodeButtonTooltip: 'Eliminar nodo',
  revealNodeTooltip: 'Desplegar',
  collapseNodeToolTip: 'Colapsar',
  createNodeButtonLabel: 'Crear',
  removeNodeButtonLabel: 'Eliminar',
  createNodeDialogTitle: 'Nuevo Nodo',
  removeNodeDialogTitle: 'Eliminar nodo',
  removeNodeConfirmation: '¿Seguro que desea eliminar este nodo?',
  nameLabel: 'Nombre',
  acceptLabel: 'Aceptar',
  cancelLabel: 'Cancelar',
  adminDialogTitle: 'Perfil',
  adminDialogContent: 'Bienvenide',
  adminDialogRoleLabel: 'Rol',
  loginButtonLabel: 'Acceder',
  logoutButtonLabel: 'Cerrar sesión',
  closeDialogLabel: 'Cerrar',
  admin: 'Administrador',
  guest: 'Invitado',
  downloadPdf: 'Descargar en PDF',
};

export default es;
