import { Translation } from '@/models/interfaces';

const en: Partial<Translation> = {
  workExperience: 'Work Experience',
  professionalHistory: 'Professional History',
  education: 'Education',
  skills: 'Skills',
  agile: 'Agile Methodologies',
  en: 'EN',
  es: 'ES',
  dropdownOptionsDownload: 'Download CV',
  dropdownOptionsClone: 'View code',
  skillsDescription:
    'I possess a diverse set of skills that enable me to deliver high-quality work.',
  workExperienceDescription: 'Explore my professional journey and the diverse roles I have held.',
  educationDescription: 'Explore my educational journey and the degrees I have obtained.',
  Projects: 'Projects',
  email: 'Email',
  phone: 'Telephone',
  languages: 'Languages',
  clickAction: 'Scroll to section',
  downloadAction: 'Click to download',
  copyAction: 'Click to copy',
  toggleThemeAction: 'Change theme',
  changeLanguageAction: 'Change language',
  scrollToHomeTooltip: 'Go to home',
  scrollToWorkTooltip: 'Go to work experience',
  scrollToEducationTooltip: 'Go to education',
  scrollToSkillsTooltip: 'Go to skills',
  scrollToProjectsTooltip: 'Go to Projects',
  createNodeButtonTooltip: 'Crreate Node',
  removeNodeButtonTooltip: 'Remove Node',
  revealNodeTooltip: 'Reveal',
  collapseNodeToolTip: 'Collapse',
  createNodeButtonLabel: 'Create',
  removeNodeButtonLabel: 'Remove',
  createNodeDialogTitle: 'New Node',
  removeNodeConfirmation: 'Are you sure you want to delete?',
  removeNodeDialogTitle: 'Remove Node',
  nameLabel: 'Name',
  acceptLabel: 'Accept',
  cancelLabel: 'Cancel',
  adminDialogTitle: 'Profile management',
  adminDialogContent: 'Welcome',
  adminDialogRoleLabel: 'Role',
  loginButtonLabel: 'Log in',
  logoutButtonLabel: 'Log out',
  closeDialogLabel: 'Close',
  admin: 'Admin',
  guest: 'Guest',
  downloadPdf: 'Download as PDF',
  activelyWorkingLabel: 'Present',
  header: 'Home',
  editLabel: 'Edit',
  editswitchlabel: 'Edit mode',
  editNetworkDialogTitle: 'Edit network',
  displayLabel: 'Display',
  urlLabel: 'URL',
  saveLabel: 'Save',
  networkUpdatedSuccess: 'Network updated',
  networkUpdatedError: 'Could not update network',
  invalidUrlError: 'Invalid URL',
  requiredFieldError: 'Required',
  addExperienceTitle: 'Add experience',
  editExperienceTitle: 'Edit experience',
  deleteExperienceTitle: 'Delete experience',
  deleteExperienceConfirmation: 'Are you sure you want to delete this experience?',
  companyNameLabel: 'Company name',
  positionLabel: 'Position',
  startDateLabel: 'Start date',
  endDateLabel: 'End date',
  experienceAddedSuccess: 'Experience added',
  experienceUpdatedSuccess: 'Experience updated',
  experienceDeletedSuccess: 'Experience deleted',
  experienceError: 'Something went wrong',
  addLabel: 'Add',
  deleteLabel: 'Delete',
  tasksLabel: 'Tasks',
  addTaskLabel: 'Add task',
};

export default en;
