import { Translation } from '@/models/interfaces';

const en: Partial<Translation> = {
  workExperience: 'Work Experience',
  professionalHistory: 'Professional History',
  education: 'Education',
  skills: 'Skills',
  agile: 'Agile Methodologies',
  en: 'EN',
  es: 'ES',
  dropdownOptionsDownload: 'Download CV',
  dropdownOptionsClone: 'View code',
  skillsDescription:
    'I possess a diverse set of skills that enable me to deliver high-quality work.',
  workExperienceDescription: 'Explore my professional journey and the diverse roles I have held.',
  educationDescription: 'Explore my educational journey and the degrees I have obtained.',
  Projects: 'Projects',
  email: 'Email',
  phone: 'Telephone',
  languages: 'Languages',
  clickAction: 'Scroll to section',
  downloadAction: 'Click to download',
  copyAction: 'Click to copy',
  toggleThemeAction: 'Change theme',
  changeLanguageAction: 'Change language',
  scrollToHomeTooltip: 'Go to home',
  scrollToWorkTooltip: 'Go to work experience',
  scrollToEducationTooltip: 'Go to education',
  scrollToSkillsTooltip: 'Go to skills',
  scrollToProjectsTooltip: 'Go to Projects',
  createNodeButtonTooltip: 'Crreate Node',
  removeNodeButtonTooltip: 'Remove Node',
  revealNodeTooltip: 'Reveal',
  collapseNodeToolTip: 'Collapse',
  createNodeButtonLabel: 'Create',
  removeNodeButtonLabel: 'Remove',
  createNodeDialogTitle: 'New Node',
  removeNodeConfirmation: 'Are you sure you want to delete?',
  removeNodeDialogTitle: 'Remove Node',
  nameLabel: 'Name',
  acceptLabel: 'Accept',
  cancelLabel: 'Cancel',
  adminDialogTitle: 'Profile management',
  adminDialogContent: 'Welcome',
  adminDialogRoleLabel: 'Role',
  loginButtonLabel: 'Log in',
  logoutButtonLabel: 'Log out',
  closeDialogLabel: 'Close',
  admin: 'Admin',
  guest: 'Guest',
  downloadPdf: 'Download as PDF',
  activelyWorkingLabel: 'Present',
  header: 'Home',
  editLabel: 'Edit',
  editswitchlabel: 'Edit',
  editNetworkDialogTitle: 'Edit network',
  displayLabel: 'Display',
  urlLabel: 'URL',
  saveLabel: 'Save',
  networkUpdatedSuccess: 'Network updated',
  networkUpdatedError: 'Could not update network',
  invalidUrlError: 'Invalid URL',
  requiredFieldError: 'Required',
  addExperienceTitle: 'Add experience',
  editExperienceTitle: 'Edit experience',
  deleteExperienceTitle: 'Delete experience',
  deleteExperienceConfirmation: 'Are you sure you want to delete this experience?',
  companyNameLabel: 'Company name',
  positionLabel: 'Position',
  startDateLabel: 'Start date',
  endDateLabel: 'End date',
  experienceAddedSuccess: 'Experience added',
  experienceUpdatedSuccess: 'Experience updated',
  experienceDeletedSuccess: 'Experience deleted',
  experienceError: 'Something went wrong',
  addLabel: 'Add',
  deleteLabel: 'Delete',
  tasksLabel: 'Tasks',
  addTaskLabel: 'Add task',
  addSkillTitle: 'Add skill',
  editSkillTitle: 'Edit skill',
  deleteSkillTitle: 'Delete skill',
  deleteSkillConfirmation: 'Are you sure you want to delete this skill?',
  skillNameLabel: 'Icon name',
  formattedNameLabel: 'Display name',
  skillAddedSuccess: 'Skill added',
  skillUpdatedSuccess: 'Skill updated',
  skillDeletedSuccess: 'Skill deleted',
  skillError: 'Something went wrong',
  addEducationTitle: 'Add education',
  editEducationTitle: 'Edit education',
  deleteEducationTitle: 'Delete education',
  deleteEducationConfirmation: 'Are you sure you want to delete this entry?',
  educationTitleLabel: 'Title',
  educationContentLabel: 'Description',
  educationAddedSuccess: 'Education added',
  educationUpdatedSuccess: 'Education updated',
  educationDeletedSuccess: 'Education deleted',
  educationError: 'Something went wrong',
  copyJsonLabel: 'Copy JSON',
  loadJsonLabel: 'Load JSON',
  loadJsonTitle: 'Load JSON',
  jsonCopiedSuccess: 'JSON copied to clipboard',
  jsonLoadedSuccess: 'JSON loaded successfully',
  jsonParseError: 'Invalid JSON',
  jsonTemplateLabel: 'Copy template',
  endDateBeforeStartError: 'End date cannot be before start date',
};

export default en;
